- name: Create Folders
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item}}"
    password: "{{jenkins_password}}"
    url: http://172.31.9.90:8080
    user: admin
  loop:
    - CIPipelines

- name: Include Pipeline Jobs File
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipelines"}
